language: node_js
node_js:
  - 'lts/*'
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
stages:
  - Validation
  - Build
jobs:
  include:
    - stage: Validation
      script:
        - yarn validate
    - stage: Build
      script:
        - yarn build
